### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by ryan-harrington**
I have made some minor refactors to the code & [`README.md`](https://github.com/Limitized/nitrogarage/blob/master/README.md).

### CODE REVIEW

**Comment by mouncg** [comment]
will check this out and resolve the conflicts.

**Comment by mouncg** [comment]
all good! will resolve.

**Comment by mouncg** [comment]
.-. git terminal gave up, will do later on tower

**Comment by ryan-harrington** [comment]
How's the status with this?

**Comment by mouncg** [comment]
never gonna be touched due to lazyness

**Pull request closed without merging**
